### ISSUE TITLE
Docker install failed: The main config file (config.cfg) does not exist.

### ISSUE THREAD

**Issue by samkong97** [LDAPAccountManager/lam#107]
When I use docker to install lam, I find it has the following problem.
![title](http://img.baible.cn/20200923015755.png)
Then I have noticed the similar issues, #95 and #83 , So I tried to run the instance without volumes and copy the config folder to the shared folder, but it still failed. In fact, the config is exist.

`docker run -p 40011:80 -it -d --name lam --volume /home/wwwroot/lam.xx.cn/data/config:/var/lib/ldap-account-manager/config --volume /home/wwwroot/lam.xx.cn/data/etc:/etc/ldap-account-manager --env LAM_SKIP_PRECONFIGURE=true ldapaccountmanager/lam:stable`

![log](http://img.baible.cn/20200923021542.png)

It can be seen that the config and etc folders both have config.cfg.

**Comment by gruberroland** [comment]
The config.cfg in .../data/config is printed in red. Maybe this is a symlink and points to a non-existing file?
I guess you can just copy the config.cfg file from .../data/etc to .../data/config. There is no need to link it on docker. LAM will read it from the config folder.

**Comment by samkong97** [comment]
Thanks for your help. Unfortunately, it cannot work with the same problem of config.cfg. When I opened this file, it has the content about config. I will take action to explore this error by analysing logs.

**Comment by wg1k** [comment]
I got the same message, and the `/var/lib/ldap-account-manager/config` folder in the container was empty (as the mounted external directory). My workaround:
Copy the config files from the `lam` docker image in a separate step, without that folder mounted, yet.

From the host machine:

```bash
CONFIG_DESTINATION="$(pwd)/volumes/lam"
mkdir -p "${CONFIG_DESTINATION}"
docker run --rm \
    --volume "${CONFIG_DESTINATION}:/config" \
    ldapaccountmanager/lam:8.0.1 \
    bash -xc "cp -ar /var/lib/ldap-account-manager/config /config"
```

Please, notice the `-a` in the `cp` command for preserving the permissions.

After that, mounting `--volume ./volumes/lam/config:/var/lib/ldap-account-manager/config` works.

A fix could be to have these files in a temporary folder in the docker image and use the docker entry-point to copy them after checking if the `/var/lib/ldap-account-manager/config` is empty because of the mount action.

**Comment by gbjuno** [comment]
same issue here. actually it's the file permission problem. apache and nginx process in container should have permission to read the config, so the volume mounted should give permission to apache or nginx. 
here's the solution to solve your problem
```
chmod -R 777 /home/wwwroot/lam.xx.cn/data/config
chmod -R 777 /home/wwwroot/lam.xx.cn/data/etc
```

**Comment by Baltimorepc** [comment]
im having this issue and i cant get it to work

**Comment by gruberroland** [comment]
@Baltimorepc this issue is already closed. Please open a new one if you still have the problem. Please add details about external volume setup, file listing of them etc.
