### ISSUE TITLE
Unable to edit user

### ISSUE THREAD

**Issue by smsc-operations** [LDAPAccountManager/lam#179]
When editing a user I get a 500 error with this in the logs:
[Mon Jul 04 16:16:20.396265 2022] [core:info] [pid 31819] [client 10.10.3.51:43926] AH00128: File does not exist: /usr/share/ldap-account-manager/lam/templates/manifest.php, referer: https://ldap.smartbit.be/templates/account/edit.php?type=user&DN=%27cn%3Dacolson%2Cou%3DUsers%2Cdc%3Dsmartbit%2Cdc%3Dbe%27

The path is not correct in /usr/share/ldap-account-manager/lam/templates/manifest.php. The lam subdir should not be there.

**Comment by gruberroland** [comment]
I think this is caused by different prefixes on your public facing proxy and the LAM installation in the background. On the proxy you have no more intermediate path like lam/login.php but on the target server it is still there.
There are two options:
* use the same prefix on all servers (e.g. "lam")
* use a rewrite rule on your proxy server to cut out the extra "lam". E.g. /lam/templates/manifest.php gets /templates/manifest.php.

**Comment by smsc-operations** [comment]
After removing the lam path everywhere we got a 200 instead of a 500 but when pressing on save we got a blank page now. However the changes are saved correctly.

**Comment by gruberroland** [comment]
Please check LAM's log for any issues reported:

https://www.ldap-account-manager.org/static/doc/manual/ch03.html#conf_logging

There might be still some issue with the rewrite rule. Please check if the request goes to the right path on the LAM server.
In general, the more easy solution would be to use the same "lam" prefix for the URLs on your proxy. You can set a redirect from "^/$" to "/lam" to open LAM whenever someone just enters the domain without prefix.
