### ISSUE TITLE
SELF SERVICE - check if user exists

### ISSUE THREAD

**Issue by informaticavera** [LDAPAccountManager/lam#294]
Would it be possible to check if the user exists using any ldap field?

In our specific case, we register people who have a unique ID or passport, and we save them in a branch of the ldap (ou=users)

When these people end their employment relationship, they are deactivated and pass a specific branch of the ldap (ou=nousers)

When registering with the self-service I understand that it is checked if the user name exists but it may be the case that the user is deactivated

**Comment by gruberroland** [comment]
The check should work if you use e.g. dc=example,dc=com instead of ou=users,dc=example,dc=com as search suffix for your profile.
If this is not an option then you could use e.g. "Attribute Uniqueness" overlay to make sure that user names are not duplicated.

https://www.openldap.org/doc/admin24/overlays.html

**Comment by informaticavera** [comment]
An option could be the preCreate script? Is there an example to generate an html error output on the self-registration page?

**Comment by gruberroland** [comment]
Indeed, the self registration service runs preCreate scripts. You can define it like this in custom scripts section:

`preCreate /some/path/myScript.sh $uid$`

Your script would need then to read the parameter and perform the LDAP search to check if uid already exists.
